import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProviders } from './theme.provider'
import AuthContext from '@/context/AuthContext'
import ToasterContext from '@/context/ToasterContext'
import SocketProvider from '@/contexts/SocketContext'
import UserProvider from '@/contexts/UserContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sparktalk',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (

    <html lang="en">

      <body className={`bg-gray-100 dark:bg-[#191D20] ${inter.className}`} >
        <AuthContext>
          <ThemeProviders>
            <ToasterContext />
            <UserProvider>
              <SocketProvider>
                {children}
                {/* <ActiveStatus /> */}
              </SocketProvider>
            </UserProvider>
          </ThemeProviders>
        </AuthContext>
      </body>
    </html >
  )
}
